const DataService = {
  getRawData() {
    return {
      upbjjList: ["Jakarta", "Surabaya", "Makassar", "Padang", "Denpasar"],
      kategoriList: ["MK Wajib", "MK Pilihan", "Praktikum", "Problem-Based"],
      pengirimanList: [
        {
          kode: "REG",
          nama: "Reguler (3-5 hari)",
        },
        {
          kode: "EXP",
          nama: "Ekspres (1-2 hari)",
        },
      ],
      paket: [
        {
          kode: "PAKET-UT-001",
          nama: "PAKET IPS Dasar",
          isi: ["EKMA4116", "EKMA4115"],
          harga: 120000,
        },
        {
          kode: "PAKET-UT-002",
          nama: "PAKET IPA Dasar",
          isi: ["BIOL4201", "FISIP4001"],
          harga: 140000,
        },
      ],
      stok: [
        {
          kode: "EKMA4116",
          judul: "Pengantar Manajemen",
          kategori: "MK Wajib",
          upbjj: "Padang",
          lokasiRak: "R1-A3",
          harga: 65000,
          qty: 28,
          safety: 20,
          image: "assets/sistem_informasi_manajemen.jpg",
          catatanHTML: "<em>Edisi 2024, cetak ulang</em>",
        },
        {
          kode: "EKMA4115",
          judul: "Pengantar Akuntansi",
          kategori: "MK Wajib",
          upbjj: "Jakarta",
          lokasiRak: "R1-A4",
          harga: 60000,
          qty: 7,
          safety: 15,
          image: "assets/pengantar_komunikasi.jpg",
          catatanHTML: "<strong>Cover baru</strong>",
        },
        {
          kode: "BIOL4201",
          judul: "Biologi Umum (Praktikum)",
          kategori: "Praktikum",
          upbjj: "Surabaya",
          lokasiRak: "R3-B2",
          harga: 80000,
          qty: 12,
          safety: 10,
          image: "assets/mikrobiologi.jpg",
          catatanHTML: "Butuh <u>pendingin</u> untuk kit basah",
        },
        {
          kode: "EKMA421",
          judul: "Kepemimpinan",
          kategori: "MK Pilihan",
          upbjj: "Makassar",
          lokasiRak: "R2-C1",
          harga: 55000,
          qty: 2,
          safety: 8,
          image: "assets/kepemimpinan.jpg",
          catatanHTML: "Stok <i>menipis</i>, prioritaskan reorder",
        },
        {
          kode: "EKMA421",
          judul: "Perkembangan Anak Usia Dini",
          kategori: "Paraktik",
          upbjj: "Semarang",
          lokasiRak: "R2-C1",
          harga: 45000,
          qty: 0,
          safety: 30,
          image: "assets/perkembangan_anak_usia_dini.jpg",
          catatanHTML: "Stok <i>menipis</i>, prioritaskan reorder",
        },
        {
          kode: "EKMA421",
          judul: "Manajemen Keuangan",
          kategori: "MK Pilihan",
          upbjj: "Makassar",
          lokasiRak: "R2-C1",
          harga: 55000,
          qty: 2,
          safety: 8,
          image: "assets/manajemen_keuangan.jpg",
          catatanHTML: "Stok <i>menipis</i>, prioritaskan reorder",
        },
      ],
      tracking: [
        {
          noDO: "DO2025-0001",
          nim: "123456789",
          nama: "Rina Wulandari",
          status: "Dalam Perjalanan",
          ekspedisi: "Reguler (3-5 hari)",
          tanggalKirim: "25 Agustus 2025",
          paket: "PAKET-UT-001",
          total: 120000,
          perjalanan: [
            {
              waktu: "2025-08-25 10:12:20",
              keterangan: "Penerimaan di Loket: TANGSEL",
            },
          ],
        },
        {
          noDO: "DO2025-0002",
          nim: "05432651",
          nama: "Agus Pranoto",
          status: "Dikirim",
          ekspedisi: "Pos Indonesia",
          tanggalKirim: "6 Juni 2026",
          paket: "PAKET-UT-002",
          total: 220000,
          perjalanan: [
            {
              waktu: "2025-08-25 10:12:20",
              keterangan:
                "Penerimaan di Loket: TANGERANG SELATAN. Pengirim: Universitas Terbuka",
            },
            {
              waktu: "2025-08-25 14:07:56",
              keterangan: "Tiba di Hub: TANGERANG SELATAN",
            },
            {
              waktu: "2025-08-25 16:30:10",
              keterangan: "Diteruskan ke Kantor Kota Bandung",
            },
            {
              waktu: "2025-08-26 12:15:33",
              keterangan: "Tiba di Hub: Kota BANDUNG",
            },
            {
              waktu: "2025-08-26 15:06:12",
              keterangan: "Proses antar ke Cimahi",
            },
            {
              waktu: "2025-08-26 20:00:00",
              keterangan: "Selesai Antar. Penerima: Agus Pranoto",
            },
          ],
        },
      ],
    };
  },
};
